name: Push Ubuntu latest to ACR

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image, tag Docker image with ACR repo, and push to ACR
      run: | 
        docker build . --file Dockerfile --tag ubuntutest:latest
        docker tag ubuntu:latest testrepomjl92.azurecr.io/test/ubuntu:latest
        docker push testrepomjl92.azurecr.io/test/ubuntu:latest
