name: Push Ubuntu latest to ACR

on: [push]

env:
  CONTAINER_REGISTRY: testrepomjl92.azurecr.io

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - uses: azure/container-actions/docker-login@master
      with:
        login-server: contoso.azurecr.io
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}

    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURECREDS  }}

    - name: Build the Docker image, tag Docker image with ACR repo, and push to ACR
      run: | 
        docker build . --file Dockerfile --tag ubuntutest:latest
        docker tag ubuntutest:latest testrepomjl92.azurecr.io/test/ubuntutest:latest
        docker push testrepomjl92.azurecr.io/test/ubuntutest:latest
