name: Push Ubuntu latest to ACR

on: [push]

env:
  CONTAINER_REGISTRY: testrepomjl92.azurecr.io

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - uses: azure/container-actions/docker-login@master
      with:
        login-server: testrepomjl92.azurecr.io
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}

    - name: Build the Docker image, tag Docker image with ACR repo, and push to ACR
      run: | 
        docker build . --tag ${{ env.CONTAINER_REGISTRY }}/ubuntutest:latest
        #docker tag ubuntutest:latest testrepomjl92.azurecr.io/test/ubuntutest:latest
        docker push ${{ env.CONTAINER_REGISTRY }}/ubuntutest:latest
